language: rust
dist: trusty
services: docker
sudo: required
  
# Setup two jobs, one for each targeted platform
matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=i686-unknown-linux-gnu

# Install tools for running tests
install:
  #- curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $TRAVIS_RUST_VERSION
  - source ~/.cargo/env
  - cargo install cross

# Run tests
script: cross test --target $TARGET

# Build and compress release
before_deploy:
  - cross build --release --target $TARGET
  - cp target/$TARGET/release/travis-docker-demo .
  - tar czf travis-docker-demo-$TARGET-$TRAVIS_BUILD_NUMBER.tar.gz travis-docker-demo
  - TRAVIS_TAG=build-$TRAVIS_BUILD_NUMBER

# Deploy to GitHub releases
deploy:
  api_key:
    secure: "F204x1y+UwJ5gti43jIjd0Uy3dtj7PTCr0kxouan9NHrhM7asyGJYjn3+x00FhzpevZKyWxkOAjK+Xajiy/wq24yaxWdR/vqmPoA4HMWHL6WA5jUMKQ4Q+eGky8cddL1GUwaBFfF2U8uIkdPzqezyPNNlsPssRhIkfdBl9AJovyox1WPtdOYqGLmG6AklndRQX5NgG/65Jl0pTUwc9G80PLhQhC/T5KbqucgpUUb8TmRNC1BWcjiplf2ZOBvTsbc1pnRqmMBzVIMVdobIowSn9SFP1LU1E/5zM1KVxuBzUam0jyX7a3QxJh8RxyY9yu8jlt4b8XQdJ63LO5/drCwORPSsgI8HPq8cGziSIM9Agq/+eIQTJHNYchULkB5E2M8Khs/Mhxj051Hr5Vbt279MKXFppdkJn9YYjTo5DM4XOQ6MsjBczzxEpiIG0U57ZdftFIlV6CMslBREAAufcAtgX+MoS8t4CqhdoBCLt+QVGlTtBeTPCzbG0rab5Gyzxe6yJiMSwkQetWYP7LoTYMZMsmhYy69NLSpGWEJvdqfoFQUyXigozq7yOCzTbzg9JDJEmut+Z3mpeOOc7NtsEFAnrc3rV8xzrOZL7JjKn6VU3icx2c2KtvEjHalC/q4ejOM4OjnoU04hL+l4etz+UjMQtMelu3nRSA2MLp4hhh0XcY="
  file: travis-docker-demo-$TARGET-$TRAVIS_BUILD_NUMBER.tar.gz
  provider: releases
  skip_cleanup: true
